GameSimulationN/Controllers/CityController.cs
using GameSimulationN.Models;
using GameSimulationN.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameSimulationN.Controllers
{
    public class CityController : Controller
    {
        private ICityRepository _repo;
        public CityController(ICityRepository repo)
        {
            _repo = repo;
        }
        //public CityController()
        //{
        //}
        public ActionResult Index()
        {
           

            return View(_repo.GetCities());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(City city)
        {
            city.GoldCoins = 10;
            _repo.Create(city);
            _repo.Save();

            return RedirectToAction("Index");

        }
        public ActionResult BuildingList(int CityId)
        {
            return RedirectToAction("List", "Building", new { id = CityId });
        }


    }
}

GameSimulationN/Views/Shared/_GoldCoinPartial.cshtml
@model GameSimulationN.Models.ViewModel.GoldCoinViewModel

@Html.DisplayFor(model => model.GoldCoins)

GameSimulationN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - City Simulator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Town", "Index", "City", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TownSimulation</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>